
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLEAN COMMA FEATURES ID LPAREN RMSE RPAREN TRANSFORMdefine : features\n            | clean\n            | transform\n            | rmsefeatures : FEATURES LPAREN RPARENclean : CLEAN LPAREN ID RPARENtransform : TRANSFORM LPAREN ID RPARENrmse : RMSE LPAREN ID COMMA ID COMMA ID RPAREN'
    
_lr_action_items = {'FEATURES':([0,],[6,]),'CLEAN':([0,],[7,]),'TRANSFORM':([0,],[8,]),'RMSE':([0,],[9,]),'$end':([1,2,3,4,5,14,18,19,24,],[0,-1,-2,-3,-4,-5,-6,-7,-8,]),'LPAREN':([6,7,8,9,],[10,11,12,13,]),'RPAREN':([10,15,16,23,],[14,18,19,24,]),'ID':([11,12,13,20,22,],[15,16,17,21,23,]),'COMMA':([17,21,],[20,22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'define':([0,],[1,]),'features':([0,],[2,]),'clean':([0,],[3,]),'transform':([0,],[4,]),'rmse':([0,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> define","S'",1,None,None,None),
  ('define -> features','define',1,'p_define','terminal.py',56),
  ('define -> clean','define',1,'p_define','terminal.py',57),
  ('define -> transform','define',1,'p_define','terminal.py',58),
  ('define -> rmse','define',1,'p_define','terminal.py',59),
  ('features -> FEATURES LPAREN RPAREN','features',3,'p_features','terminal.py',65),
  ('clean -> CLEAN LPAREN ID RPAREN','clean',4,'p_clean','terminal.py',70),
  ('transform -> TRANSFORM LPAREN ID RPAREN','transform',4,'p_transform','terminal.py',79),
  ('rmse -> RMSE LPAREN ID COMMA ID COMMA ID RPAREN','rmse',8,'p_rmse','terminal.py',85),
]
